### PR TITLE
Implemented full screen

### PR DESCRIPTION
**Pull request by ashish-nagmoti**
"Hello,

I tried to make game work on full screen
Would you kindly consider reviewing and merging this branch? Your assistance in ensuring the quality of our documentation is greatly appreciated.

Thank you in advance for your help!"

### CODE REVIEW

**Comment by ashish-nagmoti** [comment]
hey @ryanpcmcquen  it's kind request to review this pr and merge

**Comment by ryanpcmcquen** [comment]
How does this affect fullscreen functionality?

**Comment by ashish-nagmoti** [comment]
i tried to make it run 
if it's not running then I can delete PR

**Comment by ryanpcmcquen** [comment]
The code you added already exists in `initialization.h`.

**Pull request closed without merging**
